# Generated by Django 5.2.7 on 2025-11-01 03:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_artistico', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='artista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestor_artistico.artista'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='descripcion',
            field=models.TextField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
