# Generated by Django 5.2.7 on 2025-11-01 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_artistico', '0002_proyecto_artista_proyecto_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='proyectos/'),
        ),
    ]
